// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eInvoice.Models.Models.DbContext;

namespace eInvoice.Models.Migrations
{
    [DbContext(typeof(eInvoiceContext))]
    [Migration("20211012213847_createDatabase")]
    partial class createDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eInvoice.Models.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("additionalInformation");

                    b.Property<string>("BranchId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("branchId");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("buildingNumber");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("country");

                    b.Property<string>("FlatNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("flatNumber");

                    b.Property<string>("Floor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("floor");

                    b.Property<string>("Governate")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("governate");

                    b.Property<string>("Landmark")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("landmark");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("postalCode");

                    b.Property<string>("RegionCity")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("regionCity");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("registrationNumber");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("street");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("company", "business");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Approach")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("approach");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("countryOfOrigin");

                    b.Property<string>("DateValidity")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dateValidity");

                    b.Property<string>("ExportPort")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("exportPort");

                    b.Property<decimal?>("GrossWeight")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("grossWeight");

                    b.Property<decimal?>("NetWeight")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("netWeight");

                    b.Property<string>("Packaging")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("packaging");

                    b.Property<string>("Terms")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("terms");

                    b.HasKey("Id");

                    b.ToTable("delivery", "business");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Invoice", b =>
                {
                    b.Property<string>("InteranlId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("interanlId");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("date")
                        .HasColumnName("dateIssued");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("deliveryId");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("documentType");

                    b.Property<string>("DocumentTypeversion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("documentTypeversion");

                    b.Property<decimal>("ExtraDiscountAmount")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("extraDiscountAmount");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("netAmount");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("paymentId");

                    b.Property<string>("ProformaInvoiceNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("proformaInvoiceNumber");

                    b.Property<string>("PurchaseOrderDescription")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("purchaseOrderDescription");

                    b.Property<string>("PurchaseOrderReference")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("purchaseOrderReference");

                    b.Property<string>("SalesOrderDescription")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("salesOrderDescription");

                    b.Property<string>("SalesOrderReference")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("salesOrderReference");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("totalAmount");

                    b.Property<decimal>("TotalDiscountAmount")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("totalDiscountAmount");

                    b.Property<decimal>("TotalItemsDiscountAmount")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("totalItemsDiscountAmount");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("totalSalesAmount");

                    b.HasKey("InteranlId")
                        .HasName("PK__invoice__1B0114ED32D54757");

                    b.HasIndex(new[] { "CompanyId" }, "IX_invoice_companyId");

                    b.HasIndex(new[] { "DeliveryId" }, "IX_invoice_deliveryId");

                    b.HasIndex(new[] { "PaymentId" }, "IX_invoice_paymentId");

                    b.ToTable("invoice", "taxes");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankAccountIban")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankAccountIBAN");

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankAccountNo");

                    b.Property<string>("BankAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankAddress");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bankName");

                    b.Property<string>("SwiftCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("swiftCode");

                    b.Property<string>("Terms")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("terms");

                    b.HasKey("Id");

                    b.ToTable("payments", "business");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Product", b =>
                {
                    b.Property<int>("Productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productid")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountEgp")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("amountEGP");

                    b.Property<decimal?>("AmountSold")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("amountSold");

                    b.Property<decimal>("CurrencyExchangeRate")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("currencyExchangeRate");

                    b.Property<string>("CurrencySold")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("currencySold");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("discountAmount");

                    b.Property<decimal?>("DiscountRate")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("discountRate");

                    b.Property<decimal?>("InternalCode")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("internalCode");

                    b.Property<string>("InvoiceInternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("invoiceInternalId");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("itemCode");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("itemType");

                    b.Property<decimal>("ItemsDiscount")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("itemsDiscount");

                    b.Property<decimal>("NetTotal")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("netTotal");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SalesTotal")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("salesTotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalTaxableFees")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("totalTaxableFees");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("unitType");

                    b.Property<decimal>("ValueDifference")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("valueDifference");

                    b.HasKey("Productid");

                    b.HasIndex(new[] { "InvoiceInternalId" }, "IX_products_invoiceInternalId");

                    b.ToTable("products", "business");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InvoiceInternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("invoiceInternalId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InvoiceInternalId" }, "IX_signatures_invoiceInternalId");

                    b.ToTable("signatures", "business");
                });

            modelBuilder.Entity("eInvoice.Models.Models.SubmittedDoc", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("InvoiceInternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("invoiceInternalId");

                    b.Property<string>("LongId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("longId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InvoiceInternalId" }, "IX_submittedDocs_invoiceInternalId");

                    b.ToTable("submittedDocs", "business");
                });

            modelBuilder.Entity("eInvoice.Models.Models.TaxType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("amount");

                    b.Property<string>("InvoiceInternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("invoiceInternalId");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("rate");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subType");

                    b.Property<string>("TaxType1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("taxType");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "InvoiceInternalId" }, "IX_taxTypes_invoiceInternalId");

                    b.ToTable("taxTypes", "taxes");
                });

            modelBuilder.Entity("eInvoice.Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", "business");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Usersdetail", b =>
                {
                    b.Property<int>("Userid")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("firstName");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fullAddress");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fullName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lastName");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("phone");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("street");

                    b.HasKey("Userid")
                        .HasName("PK__usersdet__CBA1B257BAC2A7B9");

                    b.ToTable("usersdetails", "business");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Invoice", b =>
                {
                    b.HasOne("eInvoice.Models.Models.Company", "Company")
                        .WithMany("Invoices")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK__invoice__company__2A4B4B5E")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eInvoice.Models.Models.Delivery", "Delivery")
                        .WithMany("Invoices")
                        .HasForeignKey("DeliveryId")
                        .HasConstraintName("FK__invoice__deliver__2C3393D0")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("eInvoice.Models.Models.Payment", "Payment")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK__invoice__payment__2B3F6F97")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("Delivery");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Product", b =>
                {
                    b.HasOne("eInvoice.Models.Models.Invoice", "InvoiceInternal")
                        .WithMany("Products")
                        .HasForeignKey("InvoiceInternalId")
                        .HasConstraintName("FK__products__invoic__31EC6D26")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceInternal");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Signature", b =>
                {
                    b.HasOne("eInvoice.Models.Models.Invoice", "InvoiceInternal")
                        .WithMany("Signatures")
                        .HasForeignKey("InvoiceInternalId")
                        .HasConstraintName("FK__signature__invoi__34C8D9D1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceInternal");
                });

            modelBuilder.Entity("eInvoice.Models.Models.SubmittedDoc", b =>
                {
                    b.HasOne("eInvoice.Models.Models.Invoice", "InvoiceInternal")
                        .WithMany("SubmittedDocs")
                        .HasForeignKey("InvoiceInternalId")
                        .HasConstraintName("FK__submitted__invoi__2F10007B")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceInternal");
                });

            modelBuilder.Entity("eInvoice.Models.Models.TaxType", b =>
                {
                    b.HasOne("eInvoice.Models.Models.Invoice", "InvoiceInternal")
                        .WithMany("TaxTypes")
                        .HasForeignKey("InvoiceInternalId")
                        .HasConstraintName("FK__taxTypes__invoic__37A5467C")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceInternal");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Usersdetail", b =>
                {
                    b.HasOne("eInvoice.Models.Models.User", "User")
                        .WithOne("Usersdetail")
                        .HasForeignKey("eInvoice.Models.Models.Usersdetail", "Userid")
                        .HasConstraintName("FK__usersdeta__fullA__5070F446")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Company", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Delivery", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Invoice", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Signatures");

                    b.Navigation("SubmittedDocs");

                    b.Navigation("TaxTypes");
                });

            modelBuilder.Entity("eInvoice.Models.Models.Payment", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("eInvoice.Models.Models.User", b =>
                {
                    b.Navigation("Usersdetail");
                });
#pragma warning restore 612, 618
        }
    }
}
